#
# Copyright (C) 2020 gSpot (https://github.com/gSpotx2f/luci-app-internet-detector)
#
# This is free software, licensed under the MIT License.
#
# MOD by Rafał Wabik (IceG)

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-internet-detector
LUCI_TITLE:=Internet detector for the LuCI status page
LUCI_DEPENDS:=+luci-mod-admin-full
PKG_MAINTAINER:=Rafał Wabik <4Rafal@gmail.com>
LUCI_PKGARCH:=all
PKG_LICENSE:=MIT
PKG_VERSION:=0.4

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
